// Login/signup
const GET_PRATOS = 'GET_PRATOS';
const ERROR = 'ERROR';
const SUCESSO = 'SUCESSO';
const SUCESSO_INGREDIENT = 'SUCESSO_INGREDIENT';
const LOADING_CHANGED = 'LOADING_CHANGED';

export {
  GET_PRATOS,
  ERROR,
  SUCESSO,
  SUCESSO_INGREDIENT,
  LOADING_CHANGED
};
