const GET_USUARIO = 'GET_USUARIO';
const UPDATE_USUARIO = 'UPDATE_USUARIO';
const LOGIN = 'LOGIN';
const ERROR = 'ERROR';
const SUCESSO = 'SUCESSO';
const LOADING_CHANGED = 'LOADING_CHANGED';
const DELETE_PRATO = 'DELETE_PRATO';
const FAVORITE = 'FAVORITE';

export {
  GET_USUARIO,
  UPDATE_USUARIO,
  LOGIN,
  ERROR,
  SUCESSO,
  LOADING_CHANGED,
  DELETE_PRATO,
  FAVORITE
};
